travis:
  secure:
    BINSTAR_TOKEN: PnqTEgc58oLqOs9FgdEaAKlip6HBXombzwtvOvtiNGGAZdIuz5fFltptIlUm1CeH7cN3mtMOhhL4cgfh2ghwvDPWuFpS9+PuqhBxQE/Y7T4zMLw8RhH6TTBBAV0KAzu8AAAp9WaPSiiWYF+dvdU2fDmbcb/qBsOCnNJgirgt6UpTFfuia8O1l+PztIq39N4W2k2Tk0GASbFyKPgCJ0OEBnby+smjM3lRtxLPEg+ydD3ys3ndVQaQRV+8bF2dbyJFIAuoldOk5g/YXMdmTXo13V+QZ0N1SHoS2pEo+/xOu41sutU9LVyaZQJJkuB5a8kdn0zUotBxLMJtl/VnU1hpHFPcqryCet9wjPuIR+KFI8hMW6mgNTaX2Q/o5X+/McwfbyV87qNbTDTy2a5gyZ08KgCtUumUnZPORvK8QWjJD+G4Lsw5O6eDftP3MnE6wM/0JkNKa8hiWnqWMXsruvx0y4ZMGco3R7+IEn08aG3YMOj9g4ae89dh/QThwwinLOrp50tX2YAeIlj5rwRy6hbJKRgYuYN0U8jgsxL7m8mq/QNGhFPVdmkLFGnt/vAKgQmcCZz5kkM+8f+aRc5n5RI7pavVVRm2BrQKlUxM+DP8vGqy6BFW1q8YEEYeKrbxpS5d/YnQFHv5NOW/8iWvZaIoF+ipKNoBYvnaK/Um0tzN3ag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
